services:
  loadings-web-api-sample:
    image: plumber
    container_name: loadings-web-api-sample
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "7860:7860"
    tty: true
    restart: always
