# Cloudflare Workers Configuration
# Worker: replicate-nanobanana
# Domain: replicate-nanobanana.skume-bioinfo.workers.dev

name = "replicate-nanobanana"
main = "cloudflare-worker-CLEAN.js"
compatibility_date = "2024-01-01"

# R2 Bucket Binding for Image Storage
# This binding makes the R2 bucket available as env.IMAGE_BUCKET in the Worker
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "nurumayu-nanobanana"

# Environment Variables (Optional)
# Uncomment to set via wrangler.toml (not recommended for secrets)
# [vars]
# ALLOWED_ORIGINS = "*"

# Secrets (set via command line)
# Run: npx wrangler secret put REPLICATE_API_TOKEN
# This stores the API token securely in Cloudflare

# Deployment Commands:
# 1. Deploy: npx wrangler deploy
# 2. Set secret: npx wrangler secret put REPLICATE_API_TOKEN
# 3. View logs: npx wrangler tail
# 4. List R2 buckets: npx wrangler r2 bucket list
# 5. Create R2 bucket: npx wrangler r2 bucket create nurumayu-nanobanana
